# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      - postgres:12-alpine
      - redis:5.0.5-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
      - run: npm install
      - name: Run tests
      - run: npm test

      env:
        NODE_ENV=test
        PORT=3333
        APP_SECRET=y8qjMD4NvL3errgmviyYhdcUyCYrg5VT

        DATABASE_URL=postgres://root:root@0.0.0.0:5432/petlostTest

        MONGO_URL=

        REDIS_HOST=0.0.0.0
        REDIS_PORT=6379
        REDIS_PASS=

        APP_URL=http://0.0.0.0:3333
        WEB_URL=http://0.0.0.0:3000

        STORAGE_TYPE=local
        S3_BUCKET=petlost-app
        AWS_URL=https://petlost-app.s3-us-west-1.amazonaws.com


