# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      redis:
        image: redis
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: root

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
        env:
          NODE_ENV: test
          PORT: 3333
          APP_SECRET: y8qjMD4NvL3errgmviyYhdcUyCYrg5VT
          DATABASE_URL: postgres://postgres:root@postgres:5432/petlostTest
          REDIS_HOST: redis
          REDIS_PORT: 6379
          APP_URL: http://0.0.0.0:3333
          WEB_URL: http://0.0.0.0:3000
          STORAGE_TYPE: local
          S3_BUCKET: petlost-app
          AWS_URL: https://petlost-app.s3-us-west-1.amazonaws.com
      - run: npm test
